# Conda environment configuration for temporalXes2Plan project
name: temporalXes2Plan

channels:
  - defaults

dependencies:
  - python=3.12
  - pip
  - pip:
    - jellyfish==1.1.3
    - matplotlib==3.9.4
    - numpy==2.1.3
    - pandas==2.2.3
    - pm4py==2.7.17
    - scikit-learn==1.6.1
    - tqdm
    - requests
    - beautifulsoup4
    - scipy
    - rustxes
    - jenkspy==0.4.1