"""Tests for planning.optic — focused on solvability classification."""
import subprocess
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

import planning.optic as optic_module


class TestOpticTimeout:
    def test_timeout_emits_timeout_solvability(self, tmp_path):
        (tmp_path / "domain.pddl").write_text("(define (domain d))", encoding="utf-8")
        (tmp_path / "problem.pddl").write_text("(define (problem p) (:domain d))", encoding="utf-8")

        with patch.object(optic_module, "is_available", return_value=True), \
             patch("subprocess.run", side_effect=subprocess.TimeoutExpired(cmd="optic", timeout=5)):
            result = optic_module.run(tmp_path, timeout=5)

        assert result["solvability"] == "timeout"
        assert result["success"] is False

    def test_timeout_message_mentions_duration(self, tmp_path):
        (tmp_path / "domain.pddl").write_text("(define (domain d))", encoding="utf-8")
        (tmp_path / "problem.pddl").write_text("(define (problem p) (:domain d))", encoding="utf-8")

        with patch.object(optic_module, "is_available", return_value=True), \
             patch("subprocess.run", side_effect=subprocess.TimeoutExpired(cmd="optic", timeout=30)):
            result = optic_module.run(tmp_path, timeout=30)

        assert "30" in result["message"]

    def test_timeout_differs_from_unsolvable_resource(self, tmp_path):
        (tmp_path / "domain.pddl").write_text("(define (domain d))", encoding="utf-8")
        (tmp_path / "problem.pddl").write_text("(define (problem p) (:domain d))", encoding="utf-8")

        with patch.object(optic_module, "is_available", return_value=True), \
             patch("subprocess.run", side_effect=subprocess.TimeoutExpired(cmd="optic", timeout=1)):
            result = optic_module.run(tmp_path, timeout=1)

        assert result["solvability"] != "unsolvable_resource"


# ---------------------------------------------------------------------------
# _parse_optic_stdout / _normalise — action-name normalisation
#
# Real PDDL action names are generated by
# encoding/transition_action_builder.py (f"execute_{act_name}"[_v{i}]) and
# encoding/domain_builder.py (f"mark_places_from_{trans_label}",
# f"execute_{tau_label}" for silent transitions — tau labels look like
# "tau_1", see parsing/model_discoverer.py). Note that *silent* transitions
# also get the "execute_" prefix, not a "tau_" prefix of their own.
# ---------------------------------------------------------------------------

REALISTIC_OPTIC_STDOUT = """
;;; Solution Found
; States evaluated: 12
; Cost: 8.001
0.000: (execute_admit_patient) [3.000]
3.000: (execute_tau_1) [0.001]
3.001: (mark_places_from_admit_patient) [0.001]
3.001: (execute_run_lab_tests_v2) [5.000]
8.001: (mark_places_from_run_lab_tests) [0.001]
Time 0.042
"""


class TestNormalise:
    def test_strips_execute_prefix(self):
        # Real action names use "execute_", not "exec_".
        assert optic_module._normalise("execute_admit_patient") == "admit_patient"

    def test_strips_variant_suffix_in_isolation(self):
        # Suffix stripping alone, no "execute_" prefix involved.
        assert optic_module._normalise("run_lab_tests_v2") == "run_lab_tests"

    def test_strips_execute_prefix_and_variant_suffix_together(self):
        assert optic_module._normalise("execute_run_lab_tests_v2") == "run_lab_tests"


class TestParseOpticStdoutActionNames:
    def test_action_names_match_sanitized_log_activity_names(self):
        """Names in `actions` must be directly comparable to
        core_utils.sanitize_name(event["concept:name"]) — this is what
        metrics_collector.sequence_alignment_score() compares them against
        (see evaluation/run_evaluation.py::_run_query)."""
        _, actions, _ = optic_module._parse_optic_stdout(REALISTIC_OPTIC_STDOUT)
        assert actions == ["admit_patient", "run_lab_tests"]

    def test_silent_tau_actions_are_excluded(self):
        _, actions, _ = optic_module._parse_optic_stdout(REALISTIC_OPTIC_STDOUT)
        assert not any("tau" in a for a in actions)

    def test_mark_places_actions_are_excluded(self):
        _, actions, _ = optic_module._parse_optic_stdout(REALISTIC_OPTIC_STDOUT)
        assert not any(a.startswith("mark_places_from_") for a in actions)

    def test_no_execute_prefix_leaks_into_actions(self):
        _, actions, _ = optic_module._parse_optic_stdout(REALISTIC_OPTIC_STDOUT)
        assert not any(a.startswith("execute_") for a in actions)

    def test_makespan_is_max_end_time_across_all_lines(self):
        # Last line to START is not necessarily the last to END for a
        # temporal plan with concurrent actions — makespan must be
        # max(timestamp + duration), not just the last line's end time.
        _, _, makespan = optic_module._parse_optic_stdout(REALISTIC_OPTIC_STDOUT)
        assert makespan == pytest.approx(8.002)


class TestParseOpticMetricsCostAndDuration:
    def test_cost_parsed_from_stdout(self):
        metrics = optic_module._parse_optic_metrics(REALISTIC_OPTIC_STDOUT, "", makespan=8.002)
        assert metrics["cost"] == pytest.approx(8.001)

    def test_duration_equals_makespan(self):
        metrics = optic_module._parse_optic_metrics(REALISTIC_OPTIC_STDOUT, "", makespan=8.002)
        assert metrics["duration"] == pytest.approx(8.002)

    def test_cost_none_when_absent(self):
        stdout = "0.000: (execute_a) [1.000]\nTime 0.01"
        metrics = optic_module._parse_optic_metrics(stdout, "", makespan=1.0)
        assert metrics["cost"] is None
