from collections import defaultdict
from typing import Any, Dict, List, Optional, Set, Tuple

import core_utils as utils
from models import EffectInfo, ParseResult, TransitionInfo, AttributeCatalogEntry
from encoding.pddl_model import (
    PDDLAction, PDDLBaseAction, PDDLCondition, PDDLDurativeAction, PDDLEffect,
)
from encoding.effect_encoder import value_to_pddl_effects

logger = utils.get_logger(__name__)


class ActionBuilder:
    """Builds PDDL actions from a ParseResult.

    Token-consumption model (two steps per transition):
      1. execute_T  — consumes all input places, marks the transition T itself.
      2. mark_places_from_T — consumes T, marks all output places atomically.
         One action per transition (covers AND-split with multiple outputs).
    Tau transitions follow the same two-step pattern.
    """

    def __init__(self, parse_result: ParseResult, use_durative: bool = False) -> None:
        self._pr = parse_result
        self._use_durative = use_durative

    def build_all(self) -> List[PDDLBaseAction]:
        """Build all PDDL actions for the domain."""
        actions: List[PDDLBaseAction] = []
        actions.extend(self._build_place_marking_actions())
        actions.extend(self._build_transition_actions())
        actions.extend(self._build_tau_actions())
        return actions

    # ------------------------------------------------------------------
    # Place-marking actions (always instantaneous)
    # ------------------------------------------------------------------

    def _build_place_marking_actions(self) -> List[PDDLAction]:
        """One action per transition: consumes transition marker, marks ALL output places."""
        trans_to_out_places: Dict[str, List[str]] = defaultdict(list)
        for place_name, predecessors in self._pr.place_predecessors.items():
            for trans_name in predecessors:
                trans_to_out_places[trans_name].append(place_name)

        # Also include tau output places
        for trans_obj, tau_label in self._pr.petri_net_model.silent_transitions.items():
            tau_name = utils.sanitize_name(tau_label)
            out_places = self._pr.petri_net_model.trans_outputs.get(trans_obj, set())
            for p in out_places:
                p_name = utils.sanitize_name(p.name)
                if p_name not in trans_to_out_places[tau_name]:
                    trans_to_out_places[tau_name].append(p_name)

        actions: List[PDDLAction] = []
        for trans_name, out_places in sorted(trans_to_out_places.items()):
            # unmark transition from which places are generated
            effects = [PDDLEffect.unmarking(trans_name)]
            for p in sorted(out_places):
                effects.append(PDDLEffect.marking(p))
            actions.append(PDDLAction(
                name=f"mark_places_from_{trans_name}",
                preconditions={PDDLCondition.marked(trans_name)},
                effects=effects,
            ))

        return actions

    # ------------------------------------------------------------------
    # Transition base actions (labeled)
    # ------------------------------------------------------------------

    def _build_transition_actions(self) -> List[PDDLBaseAction]:
        """One base action per labeled transition."""
        actions: List[PDDLBaseAction] = []

        for trans_name, info in sorted(self._pr.transitions.items()):
            preconditions = self._transition_preconditions(trans_name)
            effects, effect_attrs = self._transition_effects(trans_name, info)

            if self._use_durative and info.duration is not None:
                actions.append(PDDLDurativeAction(
                    name=f"execute_{trans_name}",
                    duration_min=info.duration.effective_min,
                    duration_max=info.duration.effective_max,
                    conditions_at_start=preconditions,
                    effects_at_end=effects,
                    effect_attributes=effect_attrs,
                ))
            else:
                actions.append(PDDLAction(
                    name=f"execute_{trans_name}",
                    preconditions=preconditions,
                    effects=effects,
                    effect_attributes=effect_attrs,
                ))

        return actions

    # ------------------------------------------------------------------
    # Tau (silent) transition actions (always instantaneous)
    # ------------------------------------------------------------------

    def _build_tau_actions(self) -> List[PDDLAction]:
        """execute_tau_N actions (clearing input places, marking tau itself).

        mark_places_from_tau_N is generated by _build_place_marking_actions.
        """
        actions: List[PDDLAction] = []

        for trans_obj, tau_label in sorted(
            self._pr.petri_net_model.silent_transitions.items(),
            key=lambda kv: kv[1],
        ):
            tau_name = utils.sanitize_name(tau_label)
            input_places = self._pr.petri_net_model.trans_inputs.get(trans_obj, set())
            preconditions = {
                PDDLCondition.marked(utils.sanitize_name(p.name))
                for p in input_places
            }
            effects = [
                PDDLEffect.unmarking(utils.sanitize_name(p.name))
                for p in input_places
            ] + [PDDLEffect.marking(tau_name)]

            actions.append(PDDLAction(
                name=f"execute_{tau_name}",
                preconditions=preconditions,
                effects=effects,
            ))

        return actions

    # ------------------------------------------------------------------
    # Preconditions & effects helpers
    # ------------------------------------------------------------------

    def _transition_preconditions(self, trans_name: str) -> Set[PDDLCondition]:
        """Build precondition set: predecessor places + structural attribute preconditions."""
        predecessor_places = self._pr.transition_predecessors.get(trans_name, [])
        preconds: Set[PDDLCondition] = {PDDLCondition.marked(p) for p in predecessor_places}

        t_info = self._pr.transitions.get(trans_name)
        if t_info:
            for guard in t_info.attribute_preconditions:
                if guard.value is not None:
                    preconds.add(PDDLCondition.attr_is(guard.attribute, guard.value))
                elif not guard.negated:
                    preconds.add(PDDLCondition.attr_true(guard.attribute))
                else:
                    preconds.add(PDDLCondition.attr_false(guard.attribute))

        return preconds

    def _transition_effects(
        self, trans_name: str, info: TransitionInfo
    ) -> Tuple[List[PDDLEffect], Set[str]]:
        """Build effect list and attribute set: clear input places, mark self, add attribute effects."""
        predecessor_places = self._pr.transition_predecessors.get(trans_name, [])
        effects: List[PDDLEffect] = [
            PDDLEffect.unmarking(p)
            for p in predecessor_places
        ]
        effects.append(PDDLEffect.marking(trans_name))
        effect_attrs: Set[str] = set()

        for attr_name, effect_info in sorted(info.effects.items()):
            det_effects = self._deterministic_effect(attr_name, effect_info)
            if det_effects is not None:
                effects.extend(det_effects)
                effect_attrs.add(attr_name)

        return effects, effect_attrs

    def _deterministic_effect(
        self, attr_name: str, effect: EffectInfo
    ) -> Optional[List[PDDLEffect]]:
        """Return PDDLEffect list if the effect is deterministic, else None.

        An effect is deterministic when both appearance_level and value_level
        are 1 (screened as certain) AND both appearance_guards and value_guards
        are None (no DT conditions needed).
        """
        if effect.appearance_level != 1 or effect.value_level != 1:
            return None
        if effect.appearance_guards is not None or effect.value_guards is not None:
            return None

        values = list(effect.value_probabilities.keys())
        if len(values) != 1:
            return None

        value = values[0]
        catalog_entry = self._pr.attribute_catalog.get(attr_name)
        if catalog_entry is None:
            logger.warning("Attribute %s not in catalog, skipping effect", attr_name)
            return None

        return value_to_pddl_effects(
            attr_name, value, catalog_entry, self._pr.negated_attributes
        )
